### ISSUE TITLE
Woocommerce 4.0 problem

### ISSUE THREAD

**Issue by erikdemarco** [bueltge/adminimize#130]
Cant hide woocoommerce's "Status" & "Extensions" After updating woocommerce to latest version

**Comment by bueltge** [comment]
Have you updated the settings page of Adminimize, so that the plugin re-read all menu items? Check the slug of this menu item, is a small word on the item at the settings page - how is that slug?
Activate the debug mode of the plugin, open the console of your browser. Switch to a backend page, not the settings page of Adminimize, and look inside the debug information for the menu items. Is the slug from the menu array the same as menu item, that is inside the settings?

**Comment by dteadmin2020** [comment]
I've had the same problem, and the slugs are the same, but specifically for Reports i.e. wc-reports, whereby it won't deactivate the Woocommerce > Reports menu option, after Woocommerce and WP updates to latest versions yesterday.  Once ticked in Adminimize, it won't hide these for my Orders Manager role.  Happy to create a new thread if I need to, but I believe the issue is the same.

**Comment by bueltge** [comment]
The version 1.11.7 should solve them. Please try after the update and send your feedback. Thx.
