### ISSUE TITLE
[Bug]: Conflict with Yoast?

### ISSUE THREAD

**Issue by davidglines** [bueltge/adminimize#150]
### Description of the bug

We are trying to hide the "SEO" menu item for Yoast, but the menu item will not be hidden. This is the only menu item not responding to Adminimize.

Have you heard of any conflicts with Yoast?

### Reproduction instructions

1. Install Yoast plugin
2. Hide SEO menu group for all roles
3. All roles still see the menu item.

### Expected behavior

Hiding the SEO menu item for all roles should hide it for all roles.

### Environment info

Adminimize 1.11.7
Chrome

### Additional context

Others seem to be having the same issue on the WP support forums. Would ideally use Adminimize for this instead of hiding it via our own plugin or theme.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bueltge** [comment]
The problem is, that Yoast SEO add a different page for the menu for different roles. You as Administrator runs with the page  `wpseo_dashboard` and the subscriber is it `wpseo_workouts`. So it is not possible for the settings page to list them. 

`remove_menu_page( 'wpseo_workouts' );` is the key to hide for subscribers. 

The fastest solution is to add this slug to the "custom option" below the default menu items. 
Add to "Your own options Slug": `WPSEO Workous`
And for "Custom Slug": `wpseo_workouts`

![image](https://user-images.githubusercontent.com/133425/164539339-2b61059f-fdd2-4994-baa0-b4dbf317663b.png)

**Comment by davidglines** [comment]
Thanks, Frank!

DG

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
