### ISSUE TITLE
A few problems at the plugin, please help!

### ISSUE THREAD

**Issue by netcik** [bueltge/Adminimize#60]
Hi guys, firstly i use adminimize plugin and i should say that thanks for the plugin!

I saw a few important problems about parts, so i wanted tell them to improve the plugin...

1- i updated to settings about "admin bar front end options".. this is for editors.. but editors can be see an option on the admin bar like that [(pict 1)](http://i.hizliresim.com/Pn5aO6.png) even if i hided it... this is very important for me! please, help! because editors can be delete all of pages! 

2- Another problem is about deleting permanently to posts... i chose an editor in my website. i don't know him, so i don't wanna that he doesn't delete posts as permanently.. i removed quick options but if he clever, he can delete it from top options like that [(pict 2)](http://i.hizliresim.com/m4GNJY.png)...

if you did the problem, please send me an email (hsyn_4472@hotmail.com) ... thank you so much for now!

**Comment by bueltge** [comment]
Hi.

thanks fro the praise. Much better is a review on the plugin page - https://wordpress.org/support/plugin/adminimize/reviews/

1- this problem should be fixed in #59, #58 
You should download this version here on github and test it. The new release comes later.

2- Remember Adminimize hide only areas, no changes on the roles about rights, capability. You can try to change the capability on the role of the editor, like with the plugin Members; remove `delete_posts` - see https://codex.wordpress.org/Roles_and_Capabilities#Editor
